### ISSUE TITLE
Api Connection Problem

### ISSUE THREAD

**Issue by oksuzgil** [mynaparrot/plugNmeet-install#18]
Hello, I was able to reach the login.html page by doing the server setup cleanly. However, when I want to access the api via postman, I get the error 

POST -> https://xx.yyyyyzzzzz.com/auth

`{
    "msg": "can't verify provided information",
    "status": false
}`

**Comment by jibon57** [comment]
You'll require to send header: https://www.plugnmeet.org/docs/api/intro

**Comment by oksuzgil** [comment]
Yes, I am sending a header, but I think it is wrong that when sending {"room_id":"room01"} to the https://plugnmeet.example.com/auth method on the https://www.plugnmeet.org/docs/api/intro page it gives an error. It should return True with the correct data. After switching to /room/create with the same data, the issue was resolved.
