### ISSUE TITLE
Support arm64

### ISSUE THREAD

**Issue by tecbr** [mynaparrot/plugNmeet-install#24]
1. On install.sh:
After the line:
wget ${CONFIG_DOWNLOAD_URL}/docker-compose.yaml -O docker-compose.yaml

Add:
sed -i -z -e "s/    image:/    platform: linux\/$ARCH\n    image:/g" docker-compose.yaml

2. Add linux/arm64 to https://hub.docker.com/r/mynaparrot/plugnmeet-etherpad

I'm trying to install on an arm64 OS and I think this should do the trick. Thanks.

**Comment by jibon57** [comment]
Etherpad doesn't support arm64
